version: '3.8'

services:
  app:
    build:
      args:
        user: laravel
        uid: 1000
    working_dir: /var/www/html
    networks:
      - laravel

  db:
    networks:
      - laravel

  nginx:
    depends_on:
      - app
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
