services:
  app:
    build:
      args:
        user: laravel
        uid: 1000
    working_dir: /var/www/html
    networks:
      - laravel

  db:
    image: mysql:8.0
    networks:
      - laravel

  nginx:
    image: nginx:1.25-alpine
    depends_on:
      - app
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
